version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://user:password@db/tasks
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tasks
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
